rules:
  - id: java.security.hardcoded-credentials
    languages: [java]
    pattern: |
      private static final String $X = "...";
    message: "Hardcoded credentials detected. Store sensitive information in secure configuration or environment variables."
    severity: ERROR
    metadata:
      category: security
      confidence: HIGH
      impact: HIGH
      cwe: ["CWE-798: Use of Hard-coded Credentials"]
      owasp: ["A07:2021 - Identification and Authentication Failures"]

  - id: java.security.insecure-http
    languages: [java]
    pattern: |
      new URL("http://...")
    message: "Insecure HTTP connection detected. Use HTTPS instead."
    severity: WARNING
    metadata:
      category: security
      confidence: HIGH
      impact: MEDIUM
      cwe: ["CWE-319: Cleartext Transmission of Sensitive Information"]
      owasp: ["A05:2021 - Security Misconfiguration"]

  - id: java.security.resource-leak
    languages: [java]
    pattern: |
      $TYPE $VAR = new $TYPE(...);
      // ... existing code ...
      // Missing $VAR.close()
    message: "Resource leak detected. Ensure resources are properly closed using try-with-resources or finally block."
    severity: WARNING
    metadata:
      category: security
      confidence: MEDIUM
      impact: MEDIUM
      cwe: ["CWE-404: Improper Resource Shutdown or Release"]

  - id: java.security.unsafe-thread-pool
    languages: [java]
    pattern: |
      ExecutorService $VAR = Executors.newFixedThreadPool(...);
      // ... existing code ...
      // Missing $VAR.shutdown()
    message: "Thread pool not properly shut down. Ensure thread pools are shut down after use."
    severity: WARNING
    metadata:
      category: security
      confidence: MEDIUM
      impact: MEDIUM
      cwe: ["CWE-404: Improper Resource Shutdown or Release"]

  - id: java.security.command-injection
    languages: [java]
    pattern: |
      Runtime.getRuntime().exec("... $X ...")
    message: "Command injection vulnerability detected. Sanitize user input before using in command execution."
    severity: ERROR
    metadata:
      category: security
      confidence: HIGH
      impact: HIGH
      cwe: ["CWE-78: OS Command Injection"]
      owasp: ["A03:2021 - Injection"]

  - id: java.security.path-traversal
    languages: [java]
    pattern: |
      new File(".../" + $X)
    message: "Path traversal vulnerability detected. Sanitize file paths and use proper path validation."
    severity: ERROR
    metadata:
      category: security
      confidence: HIGH
      impact: HIGH
      cwe: ["CWE-22: Path Traversal"]
      owasp: ["A01:2021 - Broken Access Control"]

  - id: java.security.unsafe-ssl
    languages: [java]
    pattern: |
      TrustManager[] trustAllCerts = new TrustManager[] {
        new X509TrustManager() {
          public X509Certificate[] getAcceptedIssuers() { return null; }
          public void checkClientTrusted(X509Certificate[] certs, String authType) { }
          public void checkServerTrusted(X509Certificate[] certs, String authType) { }
        }
      };
    message: "Unsafe SSL/TLS configuration detected. Trusting all certificates is dangerous. Use proper certificate validation."
    severity: ERROR
    metadata:
      category: security
      confidence: HIGH
      impact: HIGH
      cwe: ["CWE-295: Improper Certificate Validation"]
      owasp: ["A05:2021 - Security Misconfiguration"]

  - id: java.security.unsafe-keystore
    languages: [java]
    pattern: |
      KeyStore ks = KeyStore.getInstance("JKS");
      ks.load(new FileInputStream($X), "password".toCharArray());
    message: "Unsafe key store loading detected. Use secure password storage and proper key management."
    severity: ERROR
    metadata:
      category: security
      confidence: HIGH
      impact: HIGH
      cwe: ["CWE-522: Insufficiently Protected Credentials"]
      owasp: ["A07:2021 - Identification and Authentication Failures"]

  - id: java.security.race-condition
    languages: [java]
    pattern: |
      int value = $VAR.get();
      // ... existing code ...
      $VAR.set(value + 1);
    message: "Potential race condition detected. Use atomic operations or proper synchronization."
    severity: WARNING
    metadata:
      category: security
      confidence: MEDIUM
      impact: MEDIUM
      cwe: ["CWE-362: Concurrent Execution using Shared Resource with Improper Synchronization"]

  - id: java.security.unsafe-exception
    languages: [java]
    pattern: |
      try {
        // ... existing code ...
      } catch (Exception e) {
        e.printStackTrace();
      }
    message: "Unsafe exception handling detected. Log exceptions properly and handle them appropriately."
    severity: WARNING
    metadata:
      category: security
      confidence: MEDIUM
      impact: MEDIUM
      cwe: ["CWE-209: Information Exposure Through an Error Message"]

  - id: java.security.unsafe-string-comparison
    languages: [java]
    pattern: |
      $X == "test"
    message: "Unsafe string comparison detected. Use equals() method for string comparison."
    severity: WARNING
    metadata:
      category: security
      confidence: HIGH
      impact: LOW
      cwe: ["CWE-595: Comparison of Object References Instead of Object Contents"]

  - id: java.security.unsafe-array-access
    languages: [java]
    pattern: |
      int value = $ARRAY[$INDEX];
    message: "Unsafe array access detected. Validate array index before access."
    severity: ERROR
    metadata:
      category: security
      confidence: HIGH
      impact: HIGH
      cwe: ["CWE-129: Improper Validation of Array Index"]

  - id: java.security.unsafe-type-cast
    languages: [java]
    pattern: |
      String str = (String) $OBJ;
    message: "Unsafe type casting detected. Validate object type before casting."
    severity: WARNING
    metadata:
      category: security
      confidence: MEDIUM
      impact: MEDIUM
      cwe: ["CWE-486: Comparison of Classes by Name"] 